"""
Prometheus ML library
"""
from __future__ import annotations
import collections.abc
import typing
__all__: list[str] = ['Adam', 'AvgPool2D', 'Conv2D', 'ConvTranspose2D', 'CosineAnnealingLR', 'Dropout', 'Embedding', 'ExponentialLR', 'Flatten', 'GRU', 'GradScaler', 'GroupNorm', 'LRScheduler', 'LSTM', 'LayerNorm', 'Linear', 'MaxPool2D', 'Module', 'MultiHeadAttention', 'PositionalEncoding', 'RMSprop', 'RNN', 'ReLU', 'SGD', 'Sequential', 'Sigmoid', 'Softmax', 'StepLR', 'Tanh', 'Tensor', 'TransformerBlock', 'abs_op', 'accuracy', 'add', 'argmax', 'bce_loss', 'broadcast_add', 'clip', 'confusion_matrix', 'contrastive_loss', 'cross_entropy_loss', 'divide', 'exp_op', 'f1_score', 'huber_loss', 'kl_divergence', 'l1_regularization', 'l2_regularization', 'log_op', 'mae_loss', 'matmul', 'max_op', 'mean', 'min_op', 'mse_loss', 'multiply', 'pow_op', 'precision', 'r2_score', 'recall', 'reconstruction_loss', 'relu', 'sigmoid', 'softmax', 'sqrt_op', 'subtract', 'sum', 'tanh_op']
class Adam:
    def __init__(self, params: collections.abc.Sequence[Tensor], lr: typing.SupportsFloat | typing.SupportsIndex = 0.0010000000474974513, beta1: typing.SupportsFloat | typing.SupportsIndex = 0.8999999761581421, beta2: typing.SupportsFloat | typing.SupportsIndex = 0.9990000128746033, eps: typing.SupportsFloat | typing.SupportsIndex = 9.99999993922529e-09) -> None:
        ...
    def step(self) -> None:
        ...
    def zero_grad(self) -> None:
        ...
    @property
    def lr(self) -> float:
        ...
    @lr.setter
    def lr(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
class AvgPool2D(Module):
    def __init__(self, kernel_size: typing.SupportsInt | typing.SupportsIndex, stride: typing.SupportsInt | typing.SupportsIndex = -1) -> None:
        ...
    def forward(self, arg0: Tensor) -> Tensor:
        ...
    def parameters(self) -> list[Tensor]:
        ...
class Conv2D(Module):
    def __init__(self, in_channels: typing.SupportsInt | typing.SupportsIndex, out_channels: typing.SupportsInt | typing.SupportsIndex, kernel_size: typing.SupportsInt | typing.SupportsIndex, stride: typing.SupportsInt | typing.SupportsIndex = 1, padding: typing.SupportsInt | typing.SupportsIndex = 0, weight_init: str = 'default') -> None:
        ...
    def forward(self, arg0: Tensor) -> Tensor:
        ...
    def parameters(self) -> list[Tensor]:
        ...
class ConvTranspose2D(Module):
    def __init__(self, in_channels: typing.SupportsInt | typing.SupportsIndex, out_channels: typing.SupportsInt | typing.SupportsIndex, kernel_size: typing.SupportsInt | typing.SupportsIndex, stride: typing.SupportsInt | typing.SupportsIndex = 1, padding: typing.SupportsInt | typing.SupportsIndex = 0, weight_init: str = 'default') -> None:
        ...
    def forward(self, arg0: Tensor) -> Tensor:
        ...
    def parameters(self) -> list[Tensor]:
        ...
class CosineAnnealingLR(LRScheduler):
    def __init__(self, base_lr: typing.SupportsFloat | typing.SupportsIndex, T_max: typing.SupportsInt | typing.SupportsIndex, min_lr: typing.SupportsFloat | typing.SupportsIndex = 0.0) -> None:
        ...
    def get_lr(self) -> float:
        ...
    def step(self) -> float:
        ...
class Dropout(Module):
    training: bool
    def __init__(self, rate: typing.SupportsFloat | typing.SupportsIndex, training: bool = True) -> None:
        ...
    def forward(self, arg0: Tensor) -> Tensor:
        ...
    def parameters(self) -> list[Tensor]:
        ...
class Embedding(Module):
    weight: Tensor
    def __init__(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def forward(self, arg0: Tensor) -> Tensor:
        ...
    def parameters(self) -> list[Tensor]:
        ...
class ExponentialLR(LRScheduler):
    def __init__(self, base_lr: typing.SupportsFloat | typing.SupportsIndex, gamma: typing.SupportsFloat | typing.SupportsIndex = 0.949999988079071) -> None:
        ...
    def get_lr(self) -> float:
        ...
    def step(self) -> float:
        ...
class Flatten(Module):
    def __init__(self) -> None:
        ...
    def forward(self, arg0: Tensor) -> Tensor:
        ...
    def parameters(self) -> list[Tensor]:
        ...
class GRU(Module):
    def __init__(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def forward(self, arg0: Tensor) -> Tensor:
        ...
    def forward_with_state(self, arg0: Tensor, arg1: Tensor) -> tuple[Tensor, Tensor]:
        ...
    def parameters(self) -> list[Tensor]:
        ...
class GradScaler:
    enabled: bool
    def __init__(self, init_scale: typing.SupportsFloat | typing.SupportsIndex = 65536.0, growth_factor: typing.SupportsFloat | typing.SupportsIndex = 2.0, backoff_factor: typing.SupportsFloat | typing.SupportsIndex = 0.5, growth_interval: typing.SupportsInt | typing.SupportsIndex = 2000, enabled: bool = True) -> None:
        ...
    def scale_loss(self, arg0: Tensor) -> Tensor:
        ...
    def unscale(self, arg0: collections.abc.Sequence[Tensor]) -> bool:
        ...
    def update(self, arg0: bool) -> None:
        ...
    @property
    def scale(self) -> float:
        ...
    @scale.setter
    def scale(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
class GroupNorm(Module):
    def __init__(self, num_groups: typing.SupportsInt | typing.SupportsIndex, num_channels: typing.SupportsInt | typing.SupportsIndex, eps: typing.SupportsFloat | typing.SupportsIndex = 9.999999747378752e-06) -> None:
        ...
    def forward(self, arg0: Tensor) -> Tensor:
        ...
    def parameters(self) -> list[Tensor]:
        ...
class LRScheduler:
    def get_lr(self) -> float:
        ...
    def step(self) -> float:
        ...
class LSTM(Module):
    def __init__(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def forward(self, arg0: Tensor) -> Tensor:
        ...
    def forward_with_state(self, arg0: Tensor, arg1: Tensor, arg2: Tensor) -> tuple[Tensor, Tensor, Tensor]:
        ...
    def parameters(self) -> list[Tensor]:
        ...
class LayerNorm(Module):
    def __init__(self, normalized_shape: typing.SupportsInt | typing.SupportsIndex, eps: typing.SupportsFloat | typing.SupportsIndex = 9.999999747378752e-06) -> None:
        ...
    def forward(self, arg0: Tensor) -> Tensor:
        ...
    def parameters(self) -> list[Tensor]:
        ...
class Linear(Module):
    bias: Tensor
    weights: Tensor
    def __init__(self, in_features: typing.SupportsInt | typing.SupportsIndex, out_features: typing.SupportsInt | typing.SupportsIndex, init: str = 'default') -> None:
        ...
    def forward(self, arg0: Tensor) -> Tensor:
        ...
    def parameters(self) -> list[Tensor]:
        ...
class MaxPool2D(Module):
    def __init__(self, kernel_size: typing.SupportsInt | typing.SupportsIndex, stride: typing.SupportsInt | typing.SupportsIndex = -1) -> None:
        ...
    def forward(self, arg0: Tensor) -> Tensor:
        ...
    def parameters(self) -> list[Tensor]:
        ...
class Module:
    def forward(self, arg0: Tensor) -> Tensor:
        ...
    def parameters(self) -> list[Tensor]:
        ...
class MultiHeadAttention(Module):
    def __init__(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def forward(self, arg0: Tensor) -> Tensor:
        ...
    def parameters(self) -> list[Tensor]:
        ...
class PositionalEncoding:
    def __init__(self, max_len: typing.SupportsInt | typing.SupportsIndex, embed_dim: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def forward(self, arg0: Tensor) -> Tensor:
        ...
class RMSprop:
    def __init__(self, params: collections.abc.Sequence[Tensor], lr: typing.SupportsFloat | typing.SupportsIndex = 0.0010000000474974513, beta: typing.SupportsFloat | typing.SupportsIndex = 0.8999999761581421, eps: typing.SupportsFloat | typing.SupportsIndex = 9.99999993922529e-09) -> None:
        ...
    def step(self) -> None:
        ...
    def zero_grad(self) -> None:
        ...
    @property
    def lr(self) -> float:
        ...
    @lr.setter
    def lr(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
class RNN(Module):
    def __init__(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def forward(self, arg0: Tensor) -> Tensor:
        ...
    def forward_with_state(self, arg0: Tensor, arg1: Tensor) -> tuple[Tensor, Tensor]:
        ...
    def parameters(self) -> list[Tensor]:
        ...
class ReLU(Module):
    def __init__(self) -> None:
        ...
    def forward(self, arg0: Tensor) -> Tensor:
        ...
    def parameters(self) -> list[Tensor]:
        ...
class SGD:
    def __init__(self, params: collections.abc.Sequence[Tensor], lr: typing.SupportsFloat | typing.SupportsIndex, momentum: typing.SupportsFloat | typing.SupportsIndex = 0.0) -> None:
        ...
    def step(self) -> None:
        ...
    def zero_grad(self) -> None:
        ...
    @property
    def lr(self) -> float:
        ...
    @lr.setter
    def lr(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
class Sequential:
    def __init__(self, arg0: list) -> None:
        ...
    def forward(self, arg0: Tensor) -> Tensor:
        ...
    def parameters(self) -> list[Tensor]:
        ...
class Sigmoid(Module):
    def __init__(self) -> None:
        ...
    def forward(self, arg0: Tensor) -> Tensor:
        ...
    def parameters(self) -> list[Tensor]:
        ...
class Softmax(Module):
    def __init__(self) -> None:
        ...
    def forward(self, arg0: Tensor) -> Tensor:
        ...
    def parameters(self) -> list[Tensor]:
        ...
class StepLR(LRScheduler):
    def __init__(self, base_lr: typing.SupportsFloat | typing.SupportsIndex, step_size: typing.SupportsInt | typing.SupportsIndex, gamma: typing.SupportsFloat | typing.SupportsIndex = 0.10000000149011612) -> None:
        ...
    def get_lr(self) -> float:
        ...
    def step(self) -> float:
        ...
class Tanh(Module):
    def __init__(self) -> None:
        ...
    def forward(self, arg0: Tensor) -> Tensor:
        ...
    def parameters(self) -> list[Tensor]:
        ...
class Tensor:
    requires_grad: bool
    @staticmethod
    def from_numpy(arg0: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], arg1: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> Tensor:
        ...
    @staticmethod
    def ones(arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> Tensor:
        ...
    @staticmethod
    def randn(arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> Tensor:
        ...
    @staticmethod
    def zeros(arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> Tensor:
        ...
    @typing.overload
    def __init__(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> None:
        ...
    @typing.overload
    def __init__(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], arg1: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]) -> None:
        ...
    def backward(self) -> None:
        ...
    def detach(self) -> Tensor:
        ...
    def fill(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    def get(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex) -> float:
        ...
    def half(self) -> Tensor:
        ...
    def num_el(self) -> int:
        ...
    def numpy(self) -> numpy.typing.NDArray[numpy.float32]:
        ...
    def print(self) -> None:
        ...
    def reset_grad(self) -> None:
        ...
    def reshape(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> Tensor:
        ...
    def set(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    def to_float(self) -> Tensor:
        ...
    def transpose(self) -> Tensor:
        ...
    @property
    def data(self) -> list[float]:
        ...
    @data.setter
    def data(self, arg0: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]) -> None:
        ...
    @property
    def grad(self) -> list[float]:
        ...
    @grad.setter
    def grad(self, arg0: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]) -> None:
        ...
    @property
    def shape(self) -> list[int]:
        ...
    @shape.setter
    def shape(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> None:
        ...
class TransformerBlock(Module):
    def __init__(self, embed_dim: typing.SupportsInt | typing.SupportsIndex, num_heads: typing.SupportsInt | typing.SupportsIndex, ff_dim: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def forward(self, arg0: Tensor) -> Tensor:
        ...
    def parameters(self) -> list[Tensor]:
        ...
def abs_op(arg0: Tensor) -> Tensor:
    ...
def accuracy(arg0: Tensor, arg1: Tensor) -> float:
    ...
@typing.overload
def add(arg0: Tensor, arg1: Tensor) -> Tensor:
    ...
@typing.overload
def add(arg0: typing.SupportsFloat | typing.SupportsIndex, arg1: Tensor) -> Tensor:
    ...
def argmax(arg0: Tensor) -> Tensor:
    ...
def bce_loss(arg0: Tensor, arg1: Tensor) -> Tensor:
    ...
def broadcast_add(arg0: Tensor, arg1: Tensor) -> Tensor:
    ...
def clip(arg0: Tensor, arg1: typing.SupportsFloat | typing.SupportsIndex, arg2: typing.SupportsFloat | typing.SupportsIndex) -> Tensor:
    ...
def confusion_matrix(arg0: Tensor, arg1: Tensor) -> Tensor:
    ...
def contrastive_loss(anchor: Tensor, positive: Tensor, negative: Tensor, margin: typing.SupportsFloat | typing.SupportsIndex = 1.0) -> Tensor:
    ...
def cross_entropy_loss(arg0: Tensor, arg1: Tensor) -> Tensor:
    ...
@typing.overload
def divide(arg0: Tensor, arg1: Tensor) -> Tensor:
    ...
@typing.overload
def divide(arg0: typing.SupportsFloat | typing.SupportsIndex, arg1: Tensor) -> Tensor:
    ...
@typing.overload
def divide(arg0: Tensor, arg1: typing.SupportsFloat | typing.SupportsIndex) -> Tensor:
    ...
def exp_op(arg0: Tensor) -> Tensor:
    ...
def f1_score(arg0: Tensor, arg1: Tensor) -> float:
    ...
def huber_loss(pred: Tensor, target: Tensor, delta: typing.SupportsFloat | typing.SupportsIndex = 1.0) -> Tensor:
    ...
def kl_divergence(arg0: Tensor, arg1: Tensor) -> Tensor:
    ...
def l1_regularization(params: collections.abc.Sequence[Tensor], lambda_: typing.SupportsFloat | typing.SupportsIndex) -> Tensor:
    ...
def l2_regularization(params: collections.abc.Sequence[Tensor], lambda_: typing.SupportsFloat | typing.SupportsIndex) -> Tensor:
    ...
def log_op(arg0: Tensor) -> Tensor:
    ...
def mae_loss(arg0: Tensor, arg1: Tensor) -> Tensor:
    ...
def matmul(arg0: Tensor, arg1: Tensor) -> Tensor:
    ...
def max_op(arg0: Tensor) -> Tensor:
    ...
def mean(a: Tensor, axis: typing.SupportsInt | typing.SupportsIndex = -1) -> Tensor:
    ...
def min_op(arg0: Tensor) -> Tensor:
    ...
def mse_loss(arg0: Tensor, arg1: Tensor) -> Tensor:
    ...
@typing.overload
def multiply(arg0: Tensor, arg1: Tensor) -> Tensor:
    ...
@typing.overload
def multiply(arg0: typing.SupportsFloat | typing.SupportsIndex, arg1: Tensor) -> Tensor:
    ...
def pow_op(arg0: Tensor, arg1: typing.SupportsFloat | typing.SupportsIndex) -> Tensor:
    ...
def precision(arg0: Tensor, arg1: Tensor) -> float:
    ...
def r2_score(arg0: Tensor, arg1: Tensor) -> float:
    ...
def recall(arg0: Tensor, arg1: Tensor) -> float:
    ...
def reconstruction_loss(arg0: Tensor, arg1: Tensor) -> Tensor:
    ...
def relu(arg0: Tensor) -> Tensor:
    ...
def sigmoid(arg0: Tensor) -> Tensor:
    ...
def softmax(arg0: Tensor) -> Tensor:
    ...
def sqrt_op(arg0: Tensor) -> Tensor:
    ...
@typing.overload
def subtract(arg0: Tensor, arg1: Tensor) -> Tensor:
    ...
@typing.overload
def subtract(arg0: typing.SupportsFloat | typing.SupportsIndex, arg1: Tensor) -> Tensor:
    ...
@typing.overload
def subtract(arg0: Tensor, arg1: typing.SupportsFloat | typing.SupportsIndex) -> Tensor:
    ...
def sum(a: Tensor, axis: typing.SupportsInt | typing.SupportsIndex = -1) -> Tensor:
    ...
def tanh_op(arg0: Tensor) -> Tensor:
    ...
