"""
Character-level text generation with an LSTM.

Trains on a short Shakespeare passage using truncated backpropagation
through time (BPTT): the corpus is split into chunks of 25 characters;
within each chunk the LSTM state is propagated forward one character at
a time and all per-step cross-entropy losses are summed before a single
backward pass.  This means training and inference use exactly the same
recurrent loop, so the model generalises correctly.

After training, new text is generated by feeding the seed one character
at a time to accumulate state, then sampling the next character from the
predicted distribution repeatedly.

Demonstrates:
    - Stateful LSTM with truncated BPTT
    - Summing per-step losses into one backward pass
    - Temperature-controlled sampling at inference time
"""

import sys, os, random, math
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

import prometheus as p

random.seed(42)

# ── Corpus ────────────────────────────────────────────────────────────────────
CORPUS = (
    "to be or not to be that is the question "
    "whether tis nobler in the mind to suffer "
    "the slings and arrows of outrageous fortune "
    "or to take arms against a sea of troubles "
    "and by opposing end them to die to sleep "
    "no more and by a sleep to say we end "
    "the heartache and the thousand natural shocks "
    "that flesh is heir to tis a consummation "
    "devoutly to be wished to die to sleep "
    "to sleep perchance to dream ay there is the rub "
    "for in that sleep of death what dreams may come "
    "when we have shuffled off this mortal coil "
    "must give us pause there is the respect "
    "that makes calamity of so long life "
    "for who would bear the whips and scorns of time "
    "the wronged love the proud mans contumely "
    "the pangs of despised love the laws delay "
    "the insolence of office and the spurns "
    "that patient merit of the unworthy takes "
    "when he himself might his quietus make "
    "with a bare bodkin who would fardels bear "
    "to grunt and sweat under a weary life "
).lower()

chars = sorted(set(CORPUS))
VOCAB = len(chars)
ch2id = {c: i for i, c in enumerate(chars)}
id2ch = {i: c for c, i in ch2id.items()}

print(f"corpus: {len(CORPUS)} chars  |  vocab: {VOCAB} unique chars")

# ── Build chunks for truncated BPTT ───────────────────────────────────────────
CHUNK = 10   # short chunks so gradients don't vanish over many LSTM steps
chunks = []  # list of (input_ids, target_ids)
for i in range(0, len(CORPUS) - CHUNK, CHUNK):
    inp = [ch2id[c] for c in CORPUS[i      : i + CHUNK    ]]
    tgt = [ch2id[c] for c in CORPUS[i + 1  : i + CHUNK + 1]]
    chunks.append((inp, tgt))

print(f"chunks: {len(chunks)} × {CHUNK} chars")

# ── Helpers ───────────────────────────────────────────────────────────────────
def one_hot(char_id):
    """Single char → Tensor [1, 1, VOCAB]."""
    flat = [0.0] * VOCAB
    flat[char_id] = 1.0
    return p.Tensor([1, 1, VOCAB], flat)

def one_hot_target(char_id):
    """Single char → one-hot Tensor [1, VOCAB] for cross-entropy."""
    flat = [0.0] * VOCAB
    flat[char_id] = 1.0
    return p.Tensor([1, VOCAB], flat)

def zeros_state():
    return p.Tensor([1, HIDDEN], [0.0] * HIDDEN)

def sample(probs_data, temperature=0.7):
    scaled = [math.exp(math.log(max(v, 1e-10)) / temperature) for v in probs_data]
    total  = sum(scaled)
    scaled = [v / total for v in scaled]
    r = random.random()
    cum = 0.0
    for i, prob in enumerate(scaled):
        cum += prob
        if r <= cum:
            return i
    return len(scaled) - 1

# ── Model ─────────────────────────────────────────────────────────────────────
HIDDEN = 64   # small hidden — corpus is tiny (466 chars)
lstm   = p.LSTM(VOCAB, HIDDEN)
linear = p.Linear(HIDDEN, VOCAB, "xavier")

params    = lstm.parameters() + linear.parameters()
optimizer = p.Adam(params, lr=0.005)
scheduler = p.StepLR(base_lr=0.005, step_size=50, gamma=0.5)

# ── Training — truncated BPTT ─────────────────────────────────────────────────
# One optimizer step per chunk (not per epoch) so the model sees many updates.
EPOCHS = 300
print(f"\n{'epoch':>6}  {'loss/char':>10}")
print("-" * 22)

for epoch in range(1, EPOCHS + 1):
    random.shuffle(chunks)
    total_loss = 0.0
    n_chars    = 0

    for inp_ids, tgt_ids in chunks:
        h = zeros_state()
        c = zeros_state()

        # First step initialises chunk_loss; remaining steps accumulate into it
        x          = one_hot(inp_ids[0])
        _, h, c    = lstm.forward_with_state(x, h, c)
        logits     = linear.forward(h)
        probs      = p.clip(p.softmax(logits), 1e-7, 1.0)
        chunk_loss = p.cross_entropy_loss(probs, one_hot_target(tgt_ids[0]))

        for t in range(1, len(inp_ids)):
            x          = one_hot(inp_ids[t])
            _, h, c    = lstm.forward_with_state(x, h, c)
            logits     = linear.forward(h)
            probs      = p.clip(p.softmax(logits), 1e-7, 1.0)
            step_loss  = p.cross_entropy_loss(probs, one_hot_target(tgt_ids[t]))
            chunk_loss = p.add(chunk_loss, step_loss)

        # Update immediately after each chunk (true truncated BPTT)
        chunk_loss.backward()
        optimizer.step()
        optimizer.zero_grad()

        total_loss += chunk_loss.data[0]
        n_chars    += len(inp_ids)

    optimizer.lr = scheduler.step()
    if epoch % 50 == 0:
        print(f"{epoch:>6}  {total_loss / n_chars:>10.4f}")

# ── Text generation ───────────────────────────────────────────────────────────
print("\n--- generated text ---")
SEED = "to be or not"
print(f"seed: '{SEED}'")

# Warm up state by encoding the seed one char at a time
h = zeros_state()
c = zeros_state()
for ch in SEED:
    x       = one_hot(ch2id[ch])
    _, h, c = lstm.forward_with_state(x, h, c)

# Generate 200 chars by sampling from the predicted distribution
gen = list(SEED)
for _ in range(200):
    x         = one_hot(ch2id[gen[-1]])
    _, h, c   = lstm.forward_with_state(x, h, c)
    logits    = linear.forward(h)
    probs     = p.softmax(logits)
    next_id   = sample(probs.data, temperature=1.0)
    gen.append(id2ch[next_id])

print("".join(gen))
